system: &System
  port: 8002   # 项目端口
  start_time: 1640966400   # 项目开始时间
  version: "1.0.0"   # 版本号
# 雪花算法配置
snow_flake: &SnowFlake
  start_time: "2023-05-01"   # 开始时间(不能大于当前时间否则返回负数）
  machine_id: 1 # 机器编号
# 系统馝钥
kev: &Key
  secret_key: "gin-insecure-013-1x84ut+1igmu8%#pjh)9!%rv+mvobon*0#d1g5!dmu$s3＃"   # 项目秘钥
  aes_key: "$bd+#e-45!+5*g&t"   # aes秘钥
# token配置
token: &Token
  expired_time: 0.5  # 过期时间（小时）
# 静态文件配置
static:
  base: &base ""
  avatar:
    - *base
    - "/avatar"
# 头像配置
avatar: &Avatar
  size: 5 # 头像大小限制(MB)
# redis配置
redis: &Redis
  prefix: "base-system" # 前缀
  password: # 密码
  default_db: 0 #默认数据率
  token_db: 1 # token DB
  verify_code_db: 2 # 滑块 DB
pgsql: &Pgsql
  db_name: "base-system"   # 数据库名称
  username: "root"   # psql账号
  password: "root"   # psql密码
  max_id_le_conns: 10   # 最大空闲连接数
  max_open_conns: 50   # 设置最大打开连校数
zap: &Zap
  director: "base-system-backend.Log" # 日志目录
  max-age: 30 # 文件最多保存多少天
  max-size: 200 # 每个日志文件保存的最大尺寸 单位：M
  max-backups: 7 # 日志文件最多保存多少个备份
# 本地开发环境配置（其他配置参照以下）
local:
  system:
    <<: *System
  snow_flake:
    <<: *SnowFlake
  key:
    <<: *Key
  token:
    <<: *Token
  static:
    base: &base  "~/programming/go/base-system-backend/static"
    avatar:
      - *base
      - "/avatar"
  avatar:
    <<: *Avatar
  redis:
    <<: *Redis
    host: "127.0.0.1"
    port: "6379"
    password: "123456" # 密码
  pgsql:
    <<: *Pgsql
    host: "127.0.0.1" # host
    port: "5432" # 端口
  zap:
    <<: *Zap
    level: "debug" # 日志等级
dev:
test:
product: