system: &System
  port: 8888   # 项目端口
  start_time: "2023-05-01"  # 项目开始时间
  version: "1.0.0"   # 版本号
# 滑块信息
captcha:
  expire: 90 # 滑块信息过期时间
  info: "captcha_water_seal" # 滑块图片水印
# 雪花算法配置
snow_flake: &SnowFlake
  start_time: "2023-05-01"   # 开始时间(不能大于当前时间否则返回负数）
  machine_id: 960 # 机器编号(0-1023)
# 系统馝钥
kev: &Key
  # 项目秘钥
  secret_key: "oksRaDFYAWlTB=b$kXotI8%fvmkN4%t7qiIj94EDNaoOo%%lkguAVQZSE%ABv7=m"
  # aes秘钥
  aes_key: "8R|+LpT6A:UlRPMz"
# token配置
token: &Token
  expired_time: 1  # 过期时间（小时）
# 静态文件配置
static: &Static
  base: &base  "./static"
  avatar:
    - *base
    - "/avatar"
  log:
    - *base
    - "/log"
# 头像配置
avatar: &Avatar
  size: 5 # 头像大小限制(MB)
# redis配置
redis: &Redis
  host: "127.0.0.1" # host
  port: "6379"
  prefix: "base-system" # 前缀
  password: # 密码
  default_db: 0 #默认数据率
  token_db: 1 # token DB
  verify_code_db: 2 # 滑块 DB
pgsql: &Pgsql
  host: "127.0.0.1" # host
  port: "5432" # 端口
  db_name: "base_system"   # 数据库名称
  username: "postgres"   # psql账号
  password: "123456"   # psql密码
  max_id_le_conns: 10   # 最大空闲连接数
  max_open_conns: 50   # 设置最大打开连校数
zap: &Zap
  director: "./logs/server.log" # 日志目录
  max-age: 30 # 文件最多保存多少天
  max-size: 200 # 每个日志文件保存的最大尺寸 单位：M
  max-backups: 7 # 日志文件最多保存多少个备份
# 本地开发环境配置（其他配置参照以下）
local: &Local
  system:
    <<: *System
  snow_flake:
    <<: *SnowFlake
  key:
    <<: *Key
  token:
    <<: *Token
  static:
    <<: *Static
  avatar:
    <<: *Avatar
  redis:
    <<: *Redis
  pgsql:
    <<: *Pgsql
  zap:
    <<: *Zap
    level: "debug" # 日志等级
dev:
  <<: *Local
  redis:
    <<: *Redis
    host: "redis"
  pgsql:
    <<: *Pgsql
    host: "postgres" # host
test:
product:
