// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/log/operate/download/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "操作日志下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "LogApi"
                ],
                "summary": "操作日志下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "action_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "end_access_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "module",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "request_ip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_access_time",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "success",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/log/operate/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "操作日志列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LogApi"
                ],
                "summary": "操作日志列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "action_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "end_access_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "module",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "request_ip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_access_time",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "success",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.OperateLogList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/privilege/:role_id/": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新角色权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PrivilegeApi"
                ],
                "summary": "更新角色权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RolePrivilegeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/privilege/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "权限列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PrivilegeApi"
                ],
                "summary": "权限列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色 ID",
                        "name": "role_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.PrivilegeList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/role/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "角色添加",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleApi"
                ],
                "summary": "角色添加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RoleCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.Create"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/role/:role_id/": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "角色修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleApi"
                ],
                "summary": "角色修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RoleUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "角色删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleApi"
                ],
                "summary": "角色删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/role/:role_id//": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "角色详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleApi"
                ],
                "summary": "角色详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/role.Role"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/role/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "角色列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleApi"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.RoleList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户创建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户创建",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.Create"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/:user_id/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询指定用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "查询指定用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UserDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改指定用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "修改指定用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserUpdateById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/avatar/": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户头像修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户头像修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/change_pwd/": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户密码修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户密码修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户密码信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserChangePwdBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/change_status/:user_id/": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改指定账户状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "修改指定账户状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户状态",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.StatusChangeById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/detail/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UserDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户修改信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "AccNormal",
                            "AccFreeze",
                            "AccChangePwd",
                            "AccStop"
                        ],
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UserList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "登录参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserLoginBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginSuccess"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/logout/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/user/reset_pwd/:user_id/": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "重置指定账号密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "重置指定账号密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token 令牌",
                        "name": "Identification",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户密码信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PwdChangeById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Data"
                        }
                    }
                }
            }
        },
        "/version/": {
            "get": {
                "description": "获取版本号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VersionApi"
                ],
                "summary": "获取版本号",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Data"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/version.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gender.Gender": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "Female": "女",
                "Male": "男"
            },
            "x-enum-varnames": [
                "Female",
                "Male"
            ]
        },
        "login.LoginType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "AccPwdLogin": "账号密码登录",
                "KeycloakLogin": "keycloak登录",
                "PhoneLogin": "手机号登录"
            },
            "x-enum-varnames": [
                "AccPwdLogin",
                "PhoneLogin",
                "KeycloakLogin"
            ]
        },
        "request.PwdChangeById": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 70
                }
            }
        },
        "request.RoleCreate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "request.RolePrivilegeUpdate": {
            "type": "object",
            "required": [
                "privilege_keys"
            ],
            "properties": {
                "privilege_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.RoleUpdate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "privilege_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.StatusChangeById": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/user.AccStatus"
                }
            }
        },
        "request.UserChangePwdBase": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/user.ChangePwdType"
                }
            }
        },
        "request.UserCreate": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string",
                    "maxLength": 20
                },
                "createTime": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/gender.Gender"
                },
                "id": {
                    "type": "integer"
                },
                "id_card": {
                    "type": "string",
                    "maxLength": 18
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 11
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "secret_key": {
                    "type": "string"
                },
                "short_name": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "request.UserLoginBase": {
            "type": "object",
            "required": [
                "login_type"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "login_type": {
                    "$ref": "#/definitions/login.LoginType"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "slider": {
                    "type": "object"
                }
            }
        },
        "request.UserUpdate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/gender.Gender"
                },
                "id_card": {
                    "type": "string",
                    "maxLength": 18
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "phone": {
                    "type": "string",
                    "maxLength": 11
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "short_name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/user.AccStatus"
                }
            }
        },
        "request.UserUpdateById": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/gender.Gender"
                },
                "id_card": {
                    "type": "string",
                    "maxLength": 18
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "short_name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/user.AccStatus"
                }
            }
        },
        "response.Create": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "response.Data": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "integer"
                },
                "status_info": {
                    "$ref": "#/definitions/response.statusInfo"
                }
            }
        },
        "response.LoginSuccess": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "id_card": {
                    "type": "string"
                },
                "is_system": {
                    "type": "boolean"
                },
                "last_time": {
                    "type": "integer"
                },
                "login_type": {
                    "$ref": "#/definitions/login.LoginType"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "privilege_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "$ref": "#/definitions/user.AccStatus"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "response.OperateLogDetail": {
            "type": "object",
            "properties": {
                "access_time": {
                    "type": "integer"
                },
                "access_url": {
                    "type": "string"
                },
                "action_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "request_ip": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "user_account": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "response.OperateLogList": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "results": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.OperateLogDetail"
                    }
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "response.PrivilegeList": {
            "type": "object",
            "properties": {
                "child_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PrivilegeList"
                    }
                },
                "dependency": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.RoleList": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.Role"
                    }
                }
            }
        },
        "response.UserDetail": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "id_card": {
                    "type": "string"
                },
                "is_system": {
                    "type": "boolean"
                },
                "last_time": {
                    "type": "integer"
                },
                "login_type": {
                    "$ref": "#/definitions/login.LoginType"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "privilege_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "$ref": "#/definitions/user.AccStatus"
                }
            }
        },
        "response.UserList": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.UserDetail"
                    }
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "response.statusInfo": {
            "type": "object",
            "properties": {
                "debug_info": {},
                "detail": {},
                "message": {}
            }
        },
        "role.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_system": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "privilege_keys": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "user.AccStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "AccNormal",
                "AccFreeze",
                "AccChangePwd",
                "AccStop"
            ]
        },
        "user.ChangePwdType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "PwdChange": "密码修改",
                "SmsChange": "手机验证码修改"
            },
            "x-enum-varnames": [
                "PwdChange",
                "SmsChange"
            ]
        },
        "version.Version": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://127.0.0.1:8001",
	BasePath:         "/v1/",
	Schemes:          []string{},
	Title:            "基础后端框架",
	Description:      "应用于快速搭建后端",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
