basePath: /v1/
definitions:
  gender.Gender:
    enum:
    - 0
    - 1
    type: integer
    x-enum-comments:
      Female: 女
      Male: 男
    x-enum-varnames:
    - Female
    - Male
  request.UserCreate:
    properties:
      account:
        maxLength: 20
        type: string
      createTime:
        type: string
      email:
        type: string
      full_name:
        type: string
      gender:
        $ref: '#/definitions/gender.Gender'
      id:
        type: integer
      id_card:
        maxLength: 18
        type: string
      name:
        maxLength: 20
        type: string
      password:
        type: string
      phone:
        maxLength: 11
        type: string
      role_ids:
        items:
          type: integer
        type: array
      secret_key:
        type: string
      short_name:
        type: string
      status:
        $ref: '#/definitions/user.AccStatus'
      updateTime:
        type: string
    required:
    - account
    - password
    type: object
  request.UserLoginBase:
    properties:
      account:
        type: string
      code:
        type: string
      login_type:
        type: integer
      password:
        type: string
      phone:
        type: string
      slider:
        type: object
    required:
    - login_type
    type: object
  response.Create:
    properties:
      id:
        type: integer
    type: object
  response.Data:
    properties:
      data: {}
      status:
        type: integer
      status_info:
        $ref: '#/definitions/response.statusInfo'
    type: object
  response.LoginSuccess:
    properties:
      accounts:
        type: string
      avatar:
        type: string
      create_time:
        type: string
      email:
        type: string
      gender:
        type: integer
      id:
        type: integer
      id_card:
        type: string
      is_system:
        type: integer
      last_time:
        type: string
      login_type:
        type: integer
      name:
        type: string
      phone:
        type: string
      privilege_list:
        items:
          type: string
        type: array
      role_ids:
        items:
          type: integer
        type: array
      status:
        $ref: '#/definitions/user.AccStatus'
      token:
        type: string
    type: object
  response.UserDetail:
    properties:
      accounts:
        type: string
      avatar:
        type: string
      create_time:
        type: string
      email:
        type: string
      gender:
        type: integer
      id:
        type: integer
      id_card:
        type: string
      is_system:
        type: integer
      last_time:
        type: string
      login_type:
        type: integer
      name:
        type: string
      phone:
        type: string
      privilege_list:
        items:
          type: string
        type: array
      role_ids:
        items:
          type: integer
        type: array
      status:
        $ref: '#/definitions/user.AccStatus'
    type: object
  response.UserList:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      results:
        items:
          $ref: '#/definitions/response.UserDetail'
        type: array
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  response.statusInfo:
    properties:
      debug_info: {}
      detail: {}
      message: {}
    type: object
  user.AccStatus:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - AccNormal
    - AccFreeze
    - AccChangePwd
    - AccStop
host: http://127.0.0.1:8001
info:
  contact: {}
  description: 应用于快速搭建后端
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 基础后端框架
  version: "1.0"
paths:
  /user/:
    post:
      consumes:
      - application/json
      description: 用户添加
      parameters:
      - description: Token 令牌
        in: header
        name: Identification
        required: true
        type: string
      - description: 用户信息
        in: body
        name: object
        schema:
          $ref: '#/definitions/request.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/response.Create'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户添加
      tags:
      - UserApi
  /user/list/:
    get:
      consumes:
      - application/json
      description: 用户列表
      parameters:
      - description: Token 令牌
        in: header
        name: Identification
        required: true
        type: string
      - in: query
        name: name
        type: string
      - in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        minimum: 1
        name: page_size
        type: integer
      - enum:
        - 0
        - 1
        - 2
        - 3
        in: query
        name: status
        type: integer
        x-enum-varnames:
        - AccNormal
        - AccFreeze
        - AccChangePwd
        - AccStop
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/response.UserList'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户列表
      tags:
      - UserApi
  /user/login/:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: Token 令牌
        in: header
        name: Identification
        required: true
        type: string
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginBase'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginSuccess'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 登录
      tags:
      - UserApi
  /user/logout/:
    post:
      consumes:
      - application/json
      description: 登出
      parameters:
      - description: Token 令牌
        in: header
        name: Identification
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 登出
      tags:
      - UserApi
swagger: "2.0"
